version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: donnaire
      POSTGRES_PASSWORD: donnaire_pass
      POSTGRES_DB: donnaire_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://donnaire:donnaire_pass@postgres:5432/donnaire_db
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET=dev_jwt_secret
      - SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: ./backend
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://donnaire:donnaire_pass@postgres:5432/donnaire_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
